"""Point-cloud file IO helpers."""

from __future__ import annotations

from pathlib import Path
from typing import BinaryIO

import numpy as np

from laclean.core.point_cloud import PointCloudData


class PointCloudIOError(RuntimeError):
    """Raised when a point-cloud file cannot be parsed."""


def read_point_cloud_file(path: Path, node_id, name: str) -> PointCloudData:
    suffix = path.suffix.lower()
    if suffix == ".ply":
        points, colors, normals = _read_ply(path)
    elif suffix in {".xyz", ".xyzn", ".xyzrgb", ".pts"}:
        points, colors, normals = _read_text_points(path, suffix)
    elif suffix == ".pcd":
        points, colors, normals = _read_pcd_with_pcl(path)
    else:
        raise PointCloudIOError(f"不支持的点云格式：{path.suffix or '<无扩展名>'}")

    if points.ndim != 2 or points.shape[1] != 3 or len(points) == 0:
        raise PointCloudIOError(f"文件中没有可用的三维点：\n{path}")

    finite_mask = np.isfinite(points).all(axis=1)
    if normals is not None and len(normals) == len(points):
        finite_mask &= np.isfinite(normals).all(axis=1)
    valid_points = np.ascontiguousarray(points[finite_mask], dtype=np.float32)
    if len(valid_points) == 0:
        raise PointCloudIOError(f"文件中的点全部为无效数值：\n{path}")

    valid_colors = None
    if colors is not None and len(colors) == len(points):
        valid_colors = np.ascontiguousarray(
            np.clip(np.rint(colors[finite_mask]), 0, 255), dtype=np.uint8
        )

    valid_normals = None
    if normals is not None and len(normals) == len(points):
        valid_normals = np.ascontiguousarray(normals[finite_mask], dtype=np.float32)

    return PointCloudData(
        node_id=node_id,
        name=name,
        asset_path=path,
        points=valid_points,
        colors=valid_colors,
        normals=valid_normals,
        unit="mm",
        invalid_points_removed=int(len(points) - len(valid_points)),
    )


def write_binary_ply(
    path: Path, data: PointCloudData, *, chunk_size: int = 250_000
) -> None:
    fields: list[tuple[str, str]] = [("x", "<f4"), ("y", "<f4"), ("z", "<f4")]
    header_properties = ["property float x", "property float y", "property float z"]
    if data.has_normals:
        fields.extend((("nx", "<f4"), ("ny", "<f4"), ("nz", "<f4")))
        header_properties.extend(
            ("property float nx", "property float ny", "property float nz")
        )
    if data.has_colors:
        fields.extend((("red", "u1"), ("green", "u1"), ("blue", "u1")))
        header_properties.extend(
            ("property uchar red", "property uchar green", "property uchar blue")
        )
    dtype = np.dtype(fields, align=False)
    header = (
        "ply\n"
        "format binary_little_endian 1.0\n"
        "comment generated by Laclean Studio\n"
        f"element vertex {data.point_count}\n"
        + "\n".join(header_properties)
        + "\nend_header\n"
    ).encode("ascii")

    with path.open("wb") as stream:
        stream.write(header)
        size = max(1, int(chunk_size))
        for start in range(0, data.point_count, size):
            stop = min(start + size, data.point_count)
            records = np.empty(stop - start, dtype=dtype)
            points = data.points[start:stop]
            records["x"], records["y"], records["z"] = points.T
            if data.has_normals:
                normals = data.normals[start:stop]
                records["nx"], records["ny"], records["nz"] = normals.T
            if data.has_colors:
                colors = data.colors[start:stop]
                records["red"], records["green"], records["blue"] = colors.T
            stream.write(records.tobytes(order="C"))
        stream.flush()


def _read_text_points(
    path: Path, suffix: str
) -> tuple[np.ndarray, np.ndarray | None, np.ndarray | None]:
    rows: list[list[float]] = []
    with path.open("r", encoding="utf-8", errors="ignore") as stream:
        for line in stream:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            parts = stripped.replace(",", " ").split()
            if suffix == ".pts" and len(parts) >= 7:
                parts = parts[1:]
            try:
                rows.append([float(value) for value in parts])
            except ValueError:
                continue
    if not rows:
        raise PointCloudIOError(f"文件中没有可用的三维点：\n{path}")
    width = max(len(row) for row in rows)
    raw = np.full((len(rows), width), np.nan, dtype=np.float32)
    for index, row in enumerate(rows):
        raw[index, : len(row)] = row
    points = raw[:, :3]
    normals = raw[:, 3:6] if suffix == ".xyzn" and raw.shape[1] >= 6 else None
    colors = raw[:, 3:6] if suffix in {".xyzrgb", ".pts"} and raw.shape[1] >= 6 else None
    return points, colors, normals


def _read_pcd_with_pcl(
    path: Path,
) -> tuple[np.ndarray, np.ndarray | None, np.ndarray | None]:
    try:
        import pcl

        cloud = pcl.load(str(path))
        points = np.ascontiguousarray(cloud.to_array()[:, :3], dtype=np.float32)
    except Exception as exc:
        raise PointCloudIOError(f"读取 PCD 点云失败：{exc}") from exc
    return points, None, None


def _read_ply(path: Path) -> tuple[np.ndarray, np.ndarray | None, np.ndarray | None]:
    with path.open("rb") as stream:
        header_lines = _read_ply_header(stream)
        vertex_count, fmt, properties = _parse_ply_header(header_lines)
        if fmt == "ascii":
            return _read_ascii_ply_vertices(stream, vertex_count, properties)
        if fmt == "binary_little_endian":
            return _read_binary_ply_vertices(stream, vertex_count, properties)
    raise PointCloudIOError(f"不支持的 PLY 格式：{fmt}")


def _read_ply_header(stream: BinaryIO) -> list[str]:
    lines: list[str] = []
    while True:
        line = stream.readline()
        if not line:
            raise PointCloudIOError("PLY 文件缺少 end_header。")
        text = line.decode("ascii", errors="replace").strip()
        lines.append(text)
        if text == "end_header":
            return lines


def _parse_ply_header(
    lines: list[str],
) -> tuple[int, str, list[tuple[str, str]]]:
    if not lines or lines[0] != "ply":
        raise PointCloudIOError("不是有效的 PLY 文件。")
    fmt = ""
    vertex_count = 0
    in_vertex = False
    properties: list[tuple[str, str]] = []
    for line in lines:
        parts = line.split()
        if len(parts) >= 3 and parts[:2] == ["format", "ascii"]:
            fmt = "ascii"
        elif len(parts) >= 3 and parts[:2] == ["format", "binary_little_endian"]:
            fmt = "binary_little_endian"
        elif len(parts) == 3 and parts[:2] == ["element", "vertex"]:
            vertex_count = int(parts[2])
            in_vertex = True
        elif len(parts) >= 2 and parts[0] == "element":
            in_vertex = False
        elif in_vertex and len(parts) == 3 and parts[0] == "property":
            properties.append((parts[2], parts[1]))
    if not fmt:
        raise PointCloudIOError("PLY 文件缺少 format。")
    if vertex_count <= 0:
        raise PointCloudIOError("PLY 文件没有 vertex 数据。")
    return vertex_count, fmt, properties


def _read_ascii_ply_vertices(
    stream: BinaryIO, vertex_count: int, properties: list[tuple[str, str]]
) -> tuple[np.ndarray, np.ndarray | None, np.ndarray | None]:
    rows: list[list[float]] = []
    for _ in range(vertex_count):
        line = stream.readline()
        if not line:
            break
        try:
            rows.append([float(value) for value in line.decode("ascii").split()])
        except ValueError:
            rows.append([])
    raw = np.asarray(rows, dtype=np.float32)
    return _split_vertex_properties(raw, properties)


def _read_binary_ply_vertices(
    stream: BinaryIO, vertex_count: int, properties: list[tuple[str, str]]
) -> tuple[np.ndarray, np.ndarray | None, np.ndarray | None]:
    dtype = np.dtype(
        [(name, _ply_numpy_dtype(kind)) for name, kind in properties], align=False
    )
    raw = np.frombuffer(stream.read(dtype.itemsize * vertex_count), dtype=dtype)
    if len(raw) != vertex_count:
        raise PointCloudIOError("PLY vertex 数据不完整。")
    columns = [np.asarray(raw[name]) for name, _ in properties]
    values = np.column_stack(columns).astype(np.float32, copy=False)
    return _split_vertex_properties(values, properties)


def _split_vertex_properties(
    values: np.ndarray, properties: list[tuple[str, str]]
) -> tuple[np.ndarray, np.ndarray | None, np.ndarray | None]:
    names = [name for name, _ in properties]
    try:
        points = values[:, [names.index("x"), names.index("y"), names.index("z")]]
    except ValueError as exc:
        raise PointCloudIOError("PLY vertex 缺少 x/y/z 属性。") from exc

    normals = None
    if all(name in names for name in ("nx", "ny", "nz")):
        normals = values[:, [names.index("nx"), names.index("ny"), names.index("nz")]]

    colors = None
    if all(name in names for name in ("red", "green", "blue")):
        colors = values[:, [names.index("red"), names.index("green"), names.index("blue")]]
    return points, colors, normals


def _ply_numpy_dtype(kind: str) -> str:
    mapping = {
        "char": "i1",
        "uchar": "u1",
        "int8": "i1",
        "uint8": "u1",
        "short": "<i2",
        "ushort": "<u2",
        "int16": "<i2",
        "uint16": "<u2",
        "int": "<i4",
        "uint": "<u4",
        "int32": "<i4",
        "uint32": "<u4",
        "float": "<f4",
        "float32": "<f4",
        "double": "<f8",
        "float64": "<f8",
    }
    try:
        return mapping[kind]
    except KeyError as exc:
        raise PointCloudIOError(f"不支持的 PLY 属性类型：{kind}") from exc
